### ISSUE TITLE
Background, introduction, and literature review review

### ISSUE THREAD

**Issue by jbae11** [jbae11/master_thesis#2]
@katyhuff  I wrote up the background, introduction and literature review part of my master's thesis.
Please let me know of any concerns you have.

Also, last time we talked, this was the preferred way of asking for review, but if you prefer any other methods (like Pull request), please let me know.

[main.1.pdf](https://github.com/jbae11/master_thesis/files/2019677/main.1.pdf)

**Comment by katyhuff** [comment]
I've glanced at it briefly and I've already noticed a few glaring things. I've listed the most obvious below. I expect higher quality text for the masters thesis review stage.

When these issues have been handled and you feel that these chapters are as good as they can possibly be (this is the standard for thesis chapter review, in my opinion), please re-request a review.

- There are grammatical errors. Please conduct a close reading, use a tool like grammarly, and/or read this aloud to yourself to identify them. I would prefer to read this when grammar issues have been handled. ("Numerous work similar to this nature exists"... ?) ("Publications... provides" mismatches the noun verb plurality)
- In what sense has ORION ever been benchmarked?
- The noun following "numerous" should not be singular. ("Numerous work", "numerous literature")
- Please use the oxford comma.
- Some of the text is overly casual/vague. I recommend a slightly more formal/specific tone. (e.g. "the largest amount of" could/should be a percentage) . 
- why does it begin with chapter 3? (List of Abbreviations and List of Symbols should not be chapters... are you really using the correct latex template for illinois theses?)
- The word "important" is overused.
- "This paper demonstrates that an analysis of a fuel cycle requires a dynamic ap- proach to measuring its metrics" <--- Is this a paper? Does this work really do that? What would be necessary to "demonstrate" that dynamica analysis is necessary? Has dynamic analysis been compared to static analysis?
- The literature review cites approximately half a dozen items and the bibliography is not present in the pdf. I expect a much more thorough literature review.
