### ISSUE TITLE
Abstract, introduction, and outline 

### ISSUE THREAD

**Issue by jbae11** [jbae11/master_thesis#3]
I wrote the abstract, introduction, and outline of the new:
`Demonstration of real-world fuel cycle transition capabilities in Cyclus, the agent-based fuel cycle simulator`.
I took the format (somewhat) from Andrei's master thesis.
Please let me know what you think.

[main.pdf](https://github.com/jbae11/master_thesis/files/2344077/main.pdf)

**Comment by katyhuff** [comment]
I'll look it over. At first glance, I always prefer a shorter title. I'm not sure that the first few words or the last few contribute. How about:

Fuel cycle transition simulation capabilities in Cyclus

**Comment by katyhuff** [comment]
The structure is fine. 

However, for just a few pages, there are a lot of grammatical errors. I know that you have the skills to recognize these errors. Please read the whole thing aloud to yourself (really) and try to send me an updated, grammatically error free version. 

I've looked over it and I see a lot of imprecise, over-general language that will need to be corrected. I recommend going through every single sentence you've written and making sure it's both accurate and precise. Some examples are below, but there are more than these.... 

- You say "Advanced fuel cycles utilize reprocessing of the UNF and advanced reactor technology." Is that statement true of all advanced fuel cycles? Do all advanced fuel cycle reprocess? Do all advanced fuel cycles incorporate advanced reactors? What's an advanced reactor anyway? Also, the statement is grammatically funky. You say the UNF... which UNF?  What does it mean to "utilize reprocessing"? Perhaps you could just say "reprocess". 
- You say "Advanced fuel cycles are much more complex than the current once-through cycle." Are they all really much more complex? From a certain perspective, fuel cycles involving breeder reactors are simpler, in many ways. Anyway, the majority of advanced fuel cycles are just slightly more complex than the once-through fuel cycle. Finally. . . once-through isn't the current fuel cycle everywhere (see: France). So, please be accurate with this phrasing "current once-through fuel cycle" which is appropriate in the US but not worldwide.
- You say "The once-through cycle is when a natural uranium source is enriched and fabricated for use in LWRs, and the UNF is stored and disposed." ... are there any other once through fuel cycles? Do CANDUs not participate in once-through fuel cycles? (hint... candu's aren't LWRs and they do participate in once through cycles)  Why just uranium... can a thorium fuel cycle be once through? When defining a term, be careful and precise.

**Comment by jbae11** [comment]
@katyhuff Here is the updated version with a (hopefully) better flow and structure. Thanks!

[main.pdf](https://github.com/jbae11/master_thesis/files/2371792/main.pdf)

**Comment by katyhuff** [comment]
Ok, I've looked over the introduction (I assume the latter chapters included aren't ready for a review yet) 
[bae-ms-round1.pdf](https://github.com/jbae11/master_thesis/files/2386071/bae-ms-round1.pdf)
. I'm going to open a new issue with my review and some specific comments.
