### ISSUE TITLE
Comments on intro

### ISSUE THREAD

**Issue by katyhuff** [jbae11/master_thesis#4]
[bae-ms-round1.pdf](https://github.com/jbae11/master_thesis/files/2386074/bae-ms-round1.pdf)

The above attached pdf has some specific comments. I appreciate that you clearly edited the first chapter for grammar. Thank you -- it was much easier to focus on the content when I wasn't editing for grammar. I stopped reading in the second chapter (I assume from the difference in grammar quality, chapter 2 was not intended to be ready for my review).

I have a few extra overarching comments. Primarily, the introduction should cover a few more concepts than it does, and the approach to literature review will need to be more deliberate and thorough. Finally -- the pdf you sent didn't include references (it included citations, but the doc stopped abruptly at page 19... so it was entirely unclear what the citation numbers were referring to). I cloned and rebuilt it separately to see them.

The main concern about the introduction, particularly the background and motivation is that there should be more emphasis on the problem and its relevance. Transition scenarios need to be explained and defined (e.g. timescales, technology transitions vs. operational or policy transitions), with their purpose and relevance to the world made clear (e.g. some transitions are materially infeasible, while others may be economically infeasible... all are of interest to decision makers). Fuel cycle simulators, also, should likely be described in the background section. Currently, the introduction merely describes two types of fuel cycles (open and closed). Firstly, modified open fuel cycles are ignored. But also, the topic of this thesis really isn't about the distinction between open and closed fuel cycles, but rather about the details of transitions to new technologies on the national level. This section needs to be expanded accordingly to capture the intersection between open and closed fuel cycles, transitions, advancement in technology, and simulators.

The second concern is that there is no compelling motivation in the Background and Motivation section. Try answering some of the following questions in the text: Why are you doing the work? Why is it interesting or important? Why would anyone want to read this thesis? How does your work (simulation of fuel cycle transitions) tie into the world energy portfolio you mention?

Finally, it would be appropriate to be more detailed and specific about your method and the cyclus method in the methods section. It may be worth including a workflow diagram in the methods section. The reader should leave the methods section understanding your research questions and approach in the context of the detailed aims and scope of the thesis.

Generally, I feel the introduction can be a short single chapter that gives an overview of the thesis, followed by chapters like Background, Literature Review, Problem Statement. Or, it could be a large chapter with those as subsections. I'm not sure really which you're going for, but I think that since this will be the ultimate document of your time here, it will need to be more rich if the goal is the latter structure.

**Comment by jbae11** [comment]
Thank you for the thorough review! I will get working on it.

**Comment by jbae11** [comment]
[main.pdf](https://github.com/jbae11/master_thesis/files/2409185/main.pdf)

I've reflected your comments and wrote more chapters (everything except for the U.S. chapter, still waiting on results from Saltproc). The benchmark and the France chapters are basically from the papers. Please let me know what you think.
